INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'У якім годзе горад Брэст атрымаў магдэбургскае права?', '1359', '1407', '1390', '1390', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N' Які з гэтых населеных пунктаў ніколі не быў абласным цэнтрам у складзе БССР?', N'Слуцк', N'Полацк', N'Пинск', N'Слуцк', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N' За ўвесь час існавання БССР колькі ў ёй вылучалася абласцей?','6', '9', '14', '9', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'У У якім годзе была створана ССРБ?', '1917', '1918', '1919', '1918', 1) 
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N' У якім годзе горад Мінск увайшоў у склад Расійскай імперыі?', '1772', '1793', '1795', '1793',1 )
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'У якім годзе горад Брэст атрымаў магдэбургскае права?', '1359', '1407', '1390', '1407', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Як называлася аперацыя па вызваленні Беларусі?', N'Уран', N'Баграціён', N'Вясновае абуджэнне', N'Вясновае абуджэнне', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Пад якім годам упершыню згадваецца Полацк?', '868', '856', '862', '856', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'У якім годзе было створана ВКЛ?', '1263', '1197', '1257', '1257', 1) 
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'У якім годзе БССР увайшла ў склад СССР?', '1918', '1922', '1917', '1922', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Колькі гадоў існавала БССР?', '72', '63','85', '72', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Колькі стагоддзяў існавала ВКЛ?','4', '5', '6', '5', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'У якім годзе была ўтворана Рэч Паспалітая?','1569' , '1573', '1551', '1569', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Хто быў першым князем ВКЛ?', N'Міндоўг', N'Віцень', N'Гедымін', N'Міндоўг', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Хто быў апошнім князем ВКЛ?', N'Аўгуст II Моцны', N'Станіслаў II Аўгуст Панятоўскі', N'Ян II Казімір Ваза', N'Станіслаў II Аўгуст Панятоўскі', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Калі ВКЛ перастала існаваць?', '1569' ,'1689', '1795', '1795', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'У якім годзе быў першы падзел Рэчы Паспалітай?', '1756', '1772', '1779', '1772', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'У якім годзе ўпершыню згадваецца Брэст??','1017','987', '1025', '1017', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N' Колькі было княстваў на тэрыторыі Беларусі?', '15' , '17', '18', '18', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'У якім годзе адбылася Грунвальдская бітва?','1410' , '1405', '1411', '1410', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Які горад стаў першай сталіцай БССР?', N'Смаленск' , N'Мінск', N'Магілёў',  N'Мінск', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Які горад стаў першай сталіцай ВКЛ?', N'Навагрудак', N'Вільня', N'Мінск', N'Навагрудак', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Калі быў вызвалены Брэст ад нямецка-фашысцкіх вайсковых падраздзяленняў?', N'29 ліпеня 1944'  ,N'25 ліпеня 1944', N'23 верасня 1943 года', N'29 ліпеня 1944', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Хто быў першым сакратаром ЦК КПБ з 1965 па 1980 гады?', N'Кірыл Трафімавіч Мазураў' , N'Панцеляймон Кандрацьевіч Панамарэнка', N'Пётр Міронавіч Машэраў', N'Пётр Міронавіч Машэраў', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Як называлася найбуйнейшае вайсковае злучэнне Рабоча-Сялянскай Чырвонай Арміі падчас Вялікай Айчыннай вайны?', N'Армія',N'Фронт', N'Дывізія', N'Фронт', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Калі пачалася Першая Сусветная вайна?',N'28 ліпеня 1914', N'1 верасня 1914', N'24 чэрвеня 1914', N'28 ліпеня 1914', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Калі пачалася Вялікая Айчынная вайна?',N'1 верасня 1939', N'22 чэрвеня 1941',N'22 ліпеня 1941', N'1 верасня 1939', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Колькі стагоддзяў існавала ВКЛ?','4', '5', '6', '5', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'У якім годзе была прынята першая Канстытуцыя Рэспублікі Беларусь?','1994'  ,'1993', '1995', '1994', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'У якім годзе адбылося аб яднанне БССР і Заходняй Беларусі?','1941' , '1922', '1939', '1939', 1) 
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'У якім годзе адбылося першае ўзбуйненне БССР?', '1926' , '1924', '1925', '1924', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Калі быў створаны Саюз Савецкіх Сацыялістычных Рэспублік?', N'30 снежня 1922' ,N'25 снежня 1922', N'27 снежня 1922', N'30 снежня 1922', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'У якім годзе прайшлі першыя прэзідэнцкія выбары ў Рэспубліцы Беларусь?','1995' ,'1994', '1991', '1994', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'У якім годзе была створана Саюзная дзяржава?', '1995', '1999', '1997', '1999', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Калі Беларусь стала адной з краін заснавальніц Арганізацыі Аб яднаных Нацый?', '1946', '1947', '1945', '1945', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'У якім годзе адбылася аварыя на ЧАЭС?', '1986'  ,'1984', '1987', '1986', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Калі скончылася Другая Сусветная вайна?', N'3 верасня 1945' , N'8 мая 1945', N'9 мая 1945', N'3 верасня 1945', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'Хто з прадстаўленых ніжэй маршалаў удзельнічаў у аперацыі "Баграціён"?', N'Ракасоўскі' ,N'Жукоў', N'Конеў', N'Ракасоўскі', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'У якім годзе быў другі падзел Рэчы Паспалітай?', '1772'  ,'1793', '1795', '1793', 1)
INSERT INTO Questions (text, ans1, ans2, ans3, correct, gr) VALUES (N'У якім годзе быў трэці падзел Рэчы Паспалітай?', '1772' ,'1793', '1795', '1795', 1)